const colors = {
  color1: [
    { value: "0", text: "0 Negro", class: "w3-black" },
    { value: "1", text: "1 Cafe", class: "w3-brown" },
    { value: "2", text: "2 Rojo", class: "w3-red" },
    { value: "3", text: "3 Naranja", class: "w3-orange" },
    { value: "4", text: "4 Amarillo", class: "w3-yellow" },
    { value: "5", text: "5 Verde", class: "w3-green" },
    { value: "6", text: "6 Azul", class: "w3-blue" },
    { value: "7", text: "7 Lila", class: "w3-purple" },
    { value: "8", text: "8 Plomo", class: "w3-gray" },
    { value: "9", text: "9 Blanco", class: "w3-white" },
  ],
  color2: [
    { value: "0", text: "0 Negro", class: "w3-black" },
    { value: "1", text: "1 Cafe", class: "w3-brown" },
    { value: "2", text: "2 Rojo", class: "w3-red" },
    { value: "3", text: "3 Naranja", class: "w3-orange" },
    { value: "4", text: "4 Amarillo", class: "w3-yellow" },
    { value: "5", text: "5 Verde", class: "w3-green" },
    { value: "6", text: "6 Azul", class: "w3-blue" },
    { value: "7", text: "7 Lila", class: "w3-purple" },
    { value: "8", text: "8 Plomo", class: "w3-gray" },
    { value: "9", text: "9 Blanco", class: "w3-white" },
  ],
  multiply: [
    { value: "0", text: "0 Negro", class: "w3-black" },
    { value: "1", text: "1 Cafe", class: "w3-brown" },
    { value: "2", text: "2 Rojo", class: "w3-red" },
    { value: "3", text: "3 Naranja", class: "w3-orange" },
    { value: "4", text: "4 Amarillo", class: "w3-yellow" },
    { value: "5", text: "5 Verde", class: "w3-green" },
    { value: "6", text: "6 Azul", class: "w3-blue" },
    { value: "7", text: "7 Lila", class: "w3-purple" },
    { value: "8", text: "8 Plomo", class: "w3-gray" },
    { value: "9", text: "9 Blanco", class: "w3-white" },
    { value: "-1", text: "-1 Dorado", class: "w3-amber" },
    { value: "-2", text: "-2 Plata", class: "w3-blue-gray" },
  ],
  tolerance: [
    { value: "1", text: "1% Cafe", class: "w3-brown" },
    { value: "2", text: "2% Rojo", class: "w3-red" },
    { value: "5", text: "5% Dorado", class: "w3-amber" },
    { value: "10", text: "10% Plata", class: "w3-blue-gray" },
    { value: "20", text: "20% Incoloro", class: "w3-white" },
  ],
};
